apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
spec:
  project: default

  source:
    repoURL: https://github.com/akylgit/ArgoCD-Demo.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    # No namespace here, ArgoCD will use default namespace for deployment

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  # Automatically create the namespace if it doesn't exist

    automated:
      selfHeal: true
      prune: true
