apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario-argo-application
  namespace: argocd  # This is the namespace where ArgoCD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/akylgit/ArgoCD-Demo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # <- Important: explicitly set to default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false  # No need to create 'default', it already exists
    automated:
      selfHeal: true
      prune: true
