
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp  # Match the app label from the deployment
  ports:
    - protocol: TCP
      port: 80          # Port exposed inside the cluster
      targetPort: 8080   # Port in the container
      nodePort: 30001    # Exposed port on all nodes in the cluster
  type: NodePort
