apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - port: 80        # External service port
      targetPort: 8080  # Internal container port
      protocol: TCP
  type: ClusterIP   # Changed from NodePort to ClusterIP
