apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1  # Number of pods to deploy
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: akdhruvin30/dhsoniweb:latest
        ports:
        - containerPort: 80  # Change container port to 80
