apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube
spec:
  replicas: 2  # Number of pods to deploy
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
      - name: youtube
        image: akyldocker25/youtube-clone:latest
        ports:
        - containerPort: 80  # Change container port to 80
