apiVersion: v1
kind: Service
metadata:
  name: youtube-service
spec:
  selector:
    app: youtube
  ports:
    - protocol: TCP
      port: 80          # Expose port 80
      targetPort: 80     # Forward to port 80 on the container
  type: ClusterIP
