apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30080  # Optional: specify or let Kubernetes choose
