apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp  # Matches the label from the deployment to the pods
  ports:
    - port: 80        # External service port (accessible within the cluster)
      targetPort: 8080  # Internal container port
      protocol: TCP
      nodePort: 30001  # Exposed NodePort for external access
  type: NodePort  # Ensures the service is exposed via NodePort
