apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario 
spec:
  replicas: 2  # Number of pods to deploy
  selector:
    matchLabels:
      app: mario 
  template:
    metadata:
      labels:
        app: mario 
    spec:
      containers:
      - name: mario 
        image: akyldocker25/mario:latest
        ports:
        - containerPort: 8080
